on:
  push:
    branches: 
      - k2p-padavan

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: init
        run: |
          sudo apt-get update
          sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd cpio git python-docutils gettext automake autopoint texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev
      - name: build
        run: |
          git clone --depth=1 https://gitee.com/hanwckf/rt-n56u.git /opt/rt-n56u
          cd /opt/rt-n56u/toolchain-mipsel
          mkdir -p toolchain-3.4.x
          wget https://github.com/hanwckf/padavan-toolchain/releases/download/v1.0/mipsel-linux-uclibc.tar.xz
          tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x
          cd /opt/rt-n56u/trunk
          wget https://raw.githubusercontent.com/felix-fly/openwrt-build/master/k2p-padavan.config -O configs/templates/K2P-5.0.config
          sed -i 's/CONFIG_MTD_STORE_PART_SIZ=0x80000/CONFIG_MTD_STORE_PART_SIZ=0x600000/' configs/boards/K2P/kernel-3.4.x.config
          sed -i 's/mtd_part_size=65536/mtd_part_size=6291456/' user/scripts/mtd_storage.sh
          sudo ./clear_tree
          sudo ./build_firmware_modify K2P-5.0
          cd /opt
          mkdir bin
          mv /opt/rt-n56u/trunk/images/*.trx bin
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: /opt/bin
